### ISSUE TITLE
Search in rig and invoice archives

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#150]
Originally reported by: **Nathan Penney (BitBucket: [NathanP1995](http://bitbucket.org/NathanP1995), GitHub: [NathanP1995](http://github.com/NathanP1995))**

---

be able to search by event name, event number and invoice number please where appropriate 

---
- Bitbucket: https://bitbucket.org/nottinghamtec/pyrigs/issue/150

**Comment by samozzy** [comment]
Closing this following the above.
