### ISSUE TITLE
All the messy data

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#158]
Originally reported by: **David Taylor (BitBucket: [davidtaylorhq](http://bitbucket.org/davidtaylorhq), GitHub: [davidtaylorhq](http://github.com/davidtaylorhq))**

---

So, as we know there is much messy data from postec RIGS.

I suggest the following "quick-fixes":

For Venues, Organisations & People:
- Delete any that do not have events associated with them (133 people, 42 organisations, 37 venues)
- Events with the venue set to 'Dry Hire', set venue to None & ensure dry-hire is True (396 events)

Then we need to go through and "merge" identical entries, by choosing a "master" copy and changing all events to point to that copy. Thoughts on the best way to do this? Do we build an interface for it? Or just do it on the command line?

---
- Bitbucket: https://bitbucket.org/nottinghamtec/pyrigs/issue/158

**Comment by johnathan99j** [comment]
Are people happy with as is now or does it need more work ? Also FYI you can now assign multiple people to an issue :smile:

**Comment by davidtaylorhq** [comment]
Sure, why not
