### ISSUE TITLE
Recent Changes Cache

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#162]
Originally reported by: **David Taylor (BitBucket: [davidtaylorhq](http://bitbucket.org/davidtaylorhq), GitHub: [davidtaylorhq](http://github.com/davidtaylorhq))**

---

This takes forever to load sometimes. I spent a while trying to optimise the code when I first made it, so I'm not sure there's much more that can be done on that front. Should be able to cache it, and only regenerate if changes are made.

---
- Bitbucket: https://bitbucket.org/nottinghamtec/pyrigs/issue/163

**Comment by FreneticScribbler** [comment]
I'm not completely sure that this is still working, wants checking...
