### ISSUE TITLE
Training record selection

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#175]
I feel there may be a better way to select records than with a templatetag. [This function](https://github.com/nottinghamtec/PyRIGS/blob/c5970d25423508a6dea98f5a9216cae126a22709/training/templatetags/training_extras.py#L11) is not very effecient, but I have been unable to get this to work from the ORM.

In an ideal world this would be a one liner, but I could live a <10 queries. This would be possible with raw SQL, but I feel this is a step too far.

**Comment by FreneticScribbler** [comment]
Weird UX, makes it look like you can have multiple milestones...
