### ISSUE TITLE
Core Event tracking

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/PyRIGS#182]
Inclusion of a checkbox, like the dry hire tick, to indicate if an event is a core event. Useful to keep track of the number of core events for statistical purposes.

**Comment by samozzy** [comment]
Stumbled across this one again:
Super easy workaround could be making a client "UoNSU Core"?

**Comment by toastmaster2k2** [comment]
Probably better as an organisation that way you keep contact details for the lead events or sports or exec officer

[cid:cm_1461067265785_1]http://www.nottinghamtec.co.uk/               Joseph Heil
TEC PA & Lightinghttp://www.nottinghamtec.co.uk/
Mobile: 07970430271
Office Tel: 0115 84 68720tel:01158468720
Emergency Mobile: 07825 065681
Portland Building, University Park, Nottingham, NG7 2RD

via CloudMagic Emailhttps://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.5.49&pv=6.0&source=email_footer_2
On Mon, Jul 11, 2016 at 12:00 PM, Sam Osborne <notifications@github.com<mailto:notifications@github.com>> wrote:

Stumbled across this one again:
Super easy workaround could be making a client "UoNSU Core"?

##

**Comment by samozzy** [comment]
Using the organisation UoNSU - Core for now.
