### ISSUE TITLE
Fixed jQuery version

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#192]
We should probably be using a fixed jQuery version rather than jquery-latest. I would advise whichever version was the latest as of a couple of days ago before @pickleshb reported potential JS issues.

**Comment by harry-bridge** [comment]
I'm interested in this issue don't worry @tomtom5152

**Comment by tomtom5152** [comment]
@pickleshb Good because I wasn't

**Comment by harry-bridge** [comment]
@tomtom5152 :camel:
