### ISSUE TITLE
Mic dropdown

### ISSUE THREAD

**Issue by nhyty** [nottinghamtec/PyRIGS#204]
Entirely broken on my phone. Won't let me search.

**Comment by samozzy** [comment]
This appears to be a problem on my phone now. Occurs on all searchable fields on the event page (person, venue, client, mic, checked in by). 
Chrome on Android on Moto G 4.

**Comment by nhyty** [comment]
It never stopped being a thing for me, I now have a Sony xperia m4 aqua. and am using the latest version of chrome

**Comment by nhyty** [comment]
This is still a really annoying bug

**Comment by davidtaylorhq** [comment]
Well once we get all the dependencies updated we can look at sorting it out. It may well be that updating the JS dependencies resolves the issue

**Comment by davidtaylorhq** [comment]
Should be fixed by #312

@samozzy please can you confirm this is fixed for you? (It works for @nhyty)

**Comment by samozzy** [comment]
Works :grinning: The tooltip doesn't go away on unfocus though.
