### ISSUE TITLE
Tooltip on notes field

### ISSUE THREAD

**Issue by davidtaylorhq** [nottinghamtec/PyRIGS#218]
Gets cut off, only seems to happen when creating a new rig - editing rigs still works fine. 

<img width="974" alt="screen shot 2016-03-31 at 23 34 38" src="https://cloud.githubusercontent.com/assets/6270921/14193041/8ba95e3a-f799-11e5-9439-ed126efe2bbd.png">

**Comment by davidtaylorhq** [comment]
Same issue with "Collected By"

**Comment by davidtaylorhq** [comment]
Need to do the same as this: 2913b25

**Comment by tomtom5152** [comment]
@davidtaylorhq you fail at issues, this is infact an issue with the MIC drop down getting hidden, nothing to do with tooltips or collected by 🔨 🔨 🔨

**Comment by johnathan99j** [comment]
Judging by the fact I can't replicate any of this I take it this can be closed ?

**Comment by davidtaylorhq** [comment]
Bye bye
