### ISSUE TITLE
Validation Error on EventItem

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#221]
> It didn't like me putting '0' in as a quantity and leaving the price blank. I was updating it, had to deal with something else so hit save on what I was doing and then the penguin happened. 

Getting a penguin of death is not ideal really, should be investigated to find the root cause of it and try and test/eliminate it.

https://app.getsentry.com/nottingham-tec/pyrigs/issues/119547580/

```
ValidationError: {'quantity': [u"'' value must be an integer."], 'cost': [u"'' value must be a decimal number."]}
(6 additional frame(s) were not displayed)
...
  File "RIGS/forms.py", line 127, in save
    items = self.process_items_json(m)
  File "RIGS/forms.py", line 92, in process_items_json
    items[pk] = self._get_or_initialise_item(pk, data[key]['fields'], event)
  File "RIGS/forms.py", line 115, in _get_or_initialise_item
    item.full_clean()
```

**Comment by FreneticScribbler** [comment]
Cannot reproduce these days. JS level validation should save people anyway unless they're dicking with it...
