### ISSUE TITLE
Tests for versioning

### ISSUE THREAD

**Issue by davidtaylorhq** [nottinghamtec/PyRIGS#222]
Need some unit tests for versioning.py, many bad things keep happening unannounced

**Comment by tomtom5152** [comment]
Whilst this does look very high tech and fancy, and I'm sure for some things it would work perfectly, for what we want I think reversion does this slightly better. I would suggest that sticking with it is the best option for now.

In terms of caching all this, I have a magic way of doing it involving binding to the post save signal of the reversion object, which then triggers the calculate function and stores it in the cache.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Yeah wasn't suggesting replacing reversion - but I would still like to refactor this into a separate app. Feel free to play with caching, I couldn't get it to work when I tried

**Comment by davidtaylorhq** [comment]
Versioning now has tests, yay
