### ISSUE TITLE
Storing Signed Paperwork on RIGS

### ISSUE THREAD

**Issue by davidtaylorhq** [nottinghamtec/PyRIGS#249]
This is definitely do-able, with not too much effort. A few design decisions we need to make:
## Storage location
1. S3 - requires fighting with treasury for a TEC AWS account, probably requires committee approval
2. SFTP to techost - not quite as good, but free

I think we should go with SFTP for now to get it working, but can then swap to S3 if we want later (just requires swapping out the django-storages module
## File format
- PDF, obviously. 

Would be nice to support converting from JPG on upload (so that you can upload a photo from a phone, or similar). Might be able to use this: https://pypi.python.org/pypi/img2pdf
## How many? & where is it registered?
1. Single 'paperwork' field on the Event model
2. Single 'paperwork' field on the Invoice model
3. Separate model to manage paperwork with foreign key to Event or Invoice - this could deal with multiple files

~~I think my vote goes to option 1 for simplicity. In theory we should never need more than 1 stored paperwork file per event - if we get a second copy, then we can probably throw away the first one~~ (see below)
### Uploading files:
1. Part of the event edit form
2. Another button on the event_detail page, which opens an uploader in a modal dialogue

I vote option 2
### Viewing files:
1. Just link to the PDF
2. Have some kind of embedded viewer

Probably option 1 to start with, maybe option 2 if it can be made pretty & efficient

---

So, any comments? 

PS: Markdown is awesome

**Comment by rbrisk** [comment]
Converting to off would be very useful.

I would vote for an extra model - but I don't have a concept of how much extra work this is

Definitely vote option 2 for uploading files.

Linking to the pdf is definitely fine. An embedded viewer would be a nice further development, but not functionally required

**Comment by rbrisk** [comment]
If it's in a separate model presumably it would then be easier to add other functionality further down the line? Ie risk assessments, rig checklists - maybe even prep lists?

**Comment by tomtom5152** [comment]
@rbrisk :camel:

**Comment by harry-bridge** [comment]
Deffo a 🌵 moment

**Comment by harry-bridge** [comment]
@rbrisk Yes this is the general idea, although give over on prep lists 😆

**Comment by tomtom5152** [comment]
@rbrisk actually had a good idea to make use of sharepoint for the file storage. Having looked into it, it would be free for us, but there is currently no package for it (that I could find)

**Comment by tomtom5152** [comment]
We now have S3 storage available, this is now trivial

**Comment by davidtaylorhq** [comment]
@tomtom5152 Well, the interface needs to be pretty

**Comment by johnathan99j** [comment]
I take it S3 has now gone away?

**Comment by davidtaylorhq** [comment]
This isn't needed now we have online authorisation
