### ISSUE TITLE
Clear date field button

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/PyRIGS#255]
Option to clear the date field. Use case: Clearing "Access from" when duplicating. Saves going through the whole thing and deleting.
A little thing that would be nice because I am lazy.

**Comment by davidtaylorhq** [comment]
@samozzy Use konami code, shoot date field, press save. Make sure not to shoot anything else ;)

**Comment by wjdp** [comment]
This will actually work, FFS

**Comment by johnathan99j** [comment]
This has at some point, appeared.

**Comment by davidtaylorhq** [comment]
Indeed, must have changed in a recent chrome update. Also has a clear button on iOS safari 😄
