### ISSUE TITLE
Paperwork terms and conditions generating 403

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#257]
Looks like this has gone very badly indeed, knew it was bound to happen at some point though.

https://app.getsentry.com/nottingham-tec/pyrigs/issues/145787941/

```
HTTPError: HTTP Error 403: Forbidden
(6 additional frame(s) were not displayed)
...
  File "RIGS/rigboard.py", line 146, in get
    terms = urllib2.urlopen(settings.TERMS_OF_HIRE_URL)

HTTPError: HTTP Error 403: Forbidden
```

**Comment by tomtom5152** [comment]
@tomtom5152 Added a pagerule to cloudflare to essentailly turn it off for terms.pdf and reloaded the proxy. Need to continue to monitor this.

Sadly you can’t whitelist heroku apps, might be worth coming up with a solution to drop the terms in the repo somehow.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Let's just put the terms in the PyRIGS  repo - easy and reliable - cross dependencies are not fun.
If they have to be in a separate repo, we could copy them into static during build...

**Comment by FreneticScribbler** [comment]
Tom's solution has worked thus far, seems fine to leave it.
