### ISSUE TITLE
Overflow on versioning

### ISSUE THREAD

**Issue by harry-bridge** [nottinghamtec/PyRIGS#259]
<img width="552" alt="screen shot 2016-08-25 at 21 06 04" src="https://cloud.githubusercontent.com/assets/5897290/17984089/cab88d12-6b07-11e6-8ba3-d6829a274ca6.png">

This happens, have fun

**Comment by davidtaylorhq** [comment]
@pickleshb Yeah, noticed this a while ago. Need to truncate it with "..." using some kind of clever logic

**Comment by davidtaylorhq** [comment]
@davidtaylorhq (Clever logic so that it still makes sure that the changes are visible)

**Comment by wjdp** [comment]
@davidtaylorhq Make the box bigger> :P

**Comment by davidtaylorhq** [comment]
@wjdp Some people write ridiculously long comments

**Comment by tomtom5152** [comment]
Doesn’t CSS have a clever truncate method in it?

Or failing that and to have a plug for Ember, it would be trivial to write a component for it that goes over all words, and anything longer than say 30 chars (or whatever width you want) gets truncated. Could even do it with links (and in Django if you must :P) to just truncate all links twitter style.

**Comment by harry-bridge** [comment]
Could try something like 
`
.truncate {
  display: block;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
` 
But I'm not sure how well that would work

**Comment by tomtom5152** [comment]
@pickleshb remove the whitespace command and this is working in chrome dev tools, although getting the popover to show to test it is not easy as the ID changes every time it disappears and you can’t use the mouse as the second you move it the popover disappears _grumble_

**Comment by davidtaylorhq** [comment]
@tomtom5152 This looks pretty, but is entirely useless because it could result in the change being missed out. (E.g. If you add some text to the bottom of the notes field)

**Comment by tomtom5152** [comment]
I feel this is a case of premature optimisation there, if a notes field is too long to physically fit on the screen, then the user can always just go to the full edit history screen to view everything.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Full edit history currently uses the same interface to view the Diffs - so the same issue will happen there

**Comment by tomtom5152** [comment]
@davidtaylorhq _much grumble_
