### ISSUE TITLE
Invoicing for inc VAT events

### ISSUE THREAD

**Issue by harry-bridge** [nottinghamtec/PyRIGS#262]
When receiving money for inc VAT events (petty cash) the event stays in the system with a negative value so you just have to pretend that there wasn't vat paid to make it go away

**Comment by davidtaylorhq** [comment]
When cash is paid into the treasury, they take the VAT off. So if you pay £20 into the machine, £16 appears in the account. My view is that RIGS should match up with the ledger, so this is desired functionality.

**Comment by pickleshb** [comment]
@davidtaylorhq Fairynuffs, just doesn't work whilst we establish our slush fund
