### ISSUE TITLE
Revisions not really revisions

### ISSUE THREAD

**Issue by harry-bridge** [nottinghamtec/PyRIGS#267]
So if you save an event without any edits done it will show last edited by person_x but person_x won't appear in the revision history, it also doesn't appear in the recent changes box

<img width="1261" alt="screen shot 2016-10-20 at 22 04 52" src="https://cloud.githubusercontent.com/assets/5897290/19577979/817fc42c-9711-11e6-856c-3874ea16b042.png">

<img width="1214" alt="screen shot 2016-10-20 at 22 04 56" src="https://cloud.githubusercontent.com/assets/5897290/19577982/8314bf90-9711-11e6-95df-eef4708280ab.png">

**Comment by davidtaylorhq** [comment]
Yes, this is true. Whenever you click "save" it saves a "revision" in the database. In the revision history & recent changes I have filtered out any revisions which don't actually make a change. I think this is sensible, although I can see how it's confusing when you look at the "last edited at" thing

**Comment by harry-bridge** [comment]
@davidtaylorhq Ross is very confused, could it also filter the last edited by too

**Comment by davidtaylorhq** [comment]
Well yes, this would be sensible. However also effort 😛

**Comment by harry-bridge** [comment]
@davidtaylorhq I'm sure you'll be bored at some point and end up doing it :P

**Comment by davidtaylorhq** [comment]
Technical reason for that is that the filtering is pretty much impossible to do on the database side. Every entry must be loaded and iterated through to check for changes. This is why the recent changes thing on the homepage is soooooo slow. Doing that every time you opened a rig would be extremely annoying.

Not saying it's unfixable, but it's not a trivial thing to do

**Comment by davidtaylorhq** [comment]
> In the revision history & recent changes I have filtered out any revisions which don't actually make a change

This is different in the new implementation. If you press save without changing anything the revision history will say something like

> Harry Bridge changed nothing useful in N02582 | Amazing Rig
