### ISSUE TITLE
Person = None issues

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#276]
Either this shouldn't be allowed (probably the best option) or the box should not show, as per [N03796](https://rigs.nottinghamtec.co.uk/event/3796/) as of today.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Effort because non-rigs are a thing

**Comment by FreneticScribbler** [comment]
Could I get more detail on this issue?

**Comment by davidtaylorhq** [comment]
@FreneticScribbler Tom wanted it to be impossible to create rigs without client contact details. Around the time of this issue being created, we had a few rigs which people put in RIGS, and then we had no way to contact the client. 

Honestly, we've managed this long, I think it's fine to retain the current behaviour

**Comment by FreneticScribbler** [comment]
I mean RIGS literally tells you if the client is purely an org, leave the person blank. Probably it shouldn't be possible to leave _both_ blank though...didn't realise you could do that!
