### ISSUE TITLE
New SU Branding

### ISSUE THREAD

**Issue by samozzy** [nottinghamtec/PyRIGS#278]
Probably want to do the #rebrand thing

**Comment by wjdp** [comment]
@samozzy nah go the other way #bringbacktheswoosh

**Comment by nhyty** [comment]
![uonsu-secondary-logo-white-rgb](https://cloud.githubusercontent.com/assets/14825903/24114423/14031f40-0d98-11e7-9701-81b5ea5114cd.png)
![uonsu-primary-logo-white-rgb](https://cloud.githubusercontent.com/assets/14825903/24114424/1404cc46-0d98-11e7-8fd8-f0505319db6c.png)

**Comment by davidtaylorhq** [comment]
Loving the white post there @nhyty 😛

**Comment by tomtom5152** [comment]
That was a PITA, and colour versions for the paperwork would be magic

**Comment by nhyty** [comment]
[UoNSU-primary-logo-CMYK.pdf](https://github.com/nottinghamtec/PyRIGS/files/855973/UoNSU-primary-logo-CMYK.pdf)
[UoNSU-secondary-logo-CMYK.pdf](https://github.com/nottinghamtec/PyRIGS/files/855974/UoNSU-secondary-logo-CMYK.pdf)

**Comment by davidtaylorhq** [comment]
@tomtom5152 did you get the new logo on the paperwork locally? Can't find a branch on github

**Comment by davidtaylorhq** [comment]
@tomtom5152 I'm sure you already got this working??

**Comment by davidtaylorhq** [comment]
@tomtom5152 bump?

**Comment by johnathan99j** [comment]
I've no idea how hard this is but may give it a try later, I have copies of the logo.

**Comment by davidtaylorhq** [comment]
I'm 90% sure Tom already got this done, but just hasn't pushed it to github. So maybe wait for him to respond before you spend the time on it. Messing with the PDF generation stuff is major effort

**Comment by FreneticScribbler** [comment]
Bit of a faff but I wouldn't call it _major_ effort...unless I missed something!

**Comment by tomtom5152** [comment]
@FreneticScribbler It wasn’t major effort, it was just very difficult to get it looking not shit...

**Comment by FreneticScribbler** [comment]
I mean, it is the SU logo, it's going to look shit either way :D 

Did take a fair few iterations to get it vaguely aligned

**Comment by FreneticScribbler** [comment]
![image](https://user-images.githubusercontent.com/3331837/72366235-c4809200-36f1-11ea-94af-ca6823ccac07.png)
This is how it looks currently, I don't hate it?
