### ISSUE TITLE
Invoice filename formatting

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#279]
When "printing" an invoice the filename doesn't include the N%05d event number which is the actually useful part. This could do with adding.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Should just be a case of copy/pasting the logic I wrote for the paperwork printing

**Comment by tomtom5152** [comment]
It's just a [oneliner](https://github.com/nottinghamtec/PyRIGS/blob/master/RIGS/finance.py#L81) that needs changing, just creating issue so I don't forget.
