### ISSUE TITLE
Online marking that RA is filled out

### ISSUE THREAD

**Issue by nhyty** [nottinghamtec/PyRIGS#281]
have a field that is a check box only accessible by the H&S people at the time that marks whether a pre-event RA has been filled out or not, makes tracking this much easier. different idea to #136

**Comment by davidtaylorhq** [comment]
@nhyty Who ticks the box? H&S or MIC?

**Comment by nhyty** [comment]
I would suggest H&S

**Comment by jerbzz** [comment]
This sounds like a good idea - and as a stopgap before full digitisation of risk assessments/checklists, how about a place to link to a scanned RA?

**Comment by FreneticScribbler** [comment]
Is (roughly) a thing. :+1:
