### ISSUE TITLE
Can't scroll inside pop up event description

### ISSUE THREAD

**Issue by johnathan99j** [nottinghamtec/PyRIGS#284]
Was on mobile (chrome) in calendar view and was looking at water polo price but couldn't scroll in the price section of the pop up screen. Had the same issues on similar events. Going to the actaul event page doesn't have this issue.

**Comment by davidtaylorhq** [comment]
Are you talking about horizontal scrolling?

**Comment by johnathan99j** [comment]
Yup

**Comment by johnathan99j** [comment]
YepOn 8 May 2017 12:05 pm, David Taylor <notifications@github.com> wrote:Are you talking about horizontal scrolling?

**Comment by FreneticScribbler** [comment]
Cannot reproduce on Chrome Mobile, Chrome and Firefox Desktop in responsive mode.
