### ISSUE TITLE
Move to Python 3

### ISSUE THREAD

**Issue by davidtaylorhq** [nottinghamtec/PyRIGS#287]
Now we're up to date per #216 🎉  we should look at moving to Python 3. I haven't done this with a project before, however I believe it should be as simple as:

- [x] Run [2 to 3](https://docs.python.org/2/library/2to3.html) converter on the codebase
- [x] Remove some `__future__` imports

And then it should work... Am I missing something @wjdp @tomtom5152. Django has some stuff [here](https://docs.djangoproject.com/en/1.11/topics/python3/) about upgrading - the main thing I see that *could* cause us issues are the unicode literals... I don't think we do anything weird like literal byte strings.

**Comment by wjdp** [comment]
For xSACdb I've been adding unicode literals via a future import for a while now (idea being do it gradually). It has kicked up some minor issues but nothing major.

Are all of your dependancies python3 ready? requires.io shows a flag next to versions, I used that.

**Comment by davidtaylorhq** [comment]
Not looking too bad:

https://requires.io/github/nottinghamtec/PyRIGS/requirements/?branch=master

I'm not convinced it's 100% accurate though - for example 

- static3's github page clearly says it is py3 compatible
- django-ical has [passing tests](https://travis-ci.org/browniebroke/django-ical) for py3

There's a lot of mess in our requirements.txt - for example:

- I can think of no reason why we'd need `yolk` in production. 
- django-toolbelt is entirely unnecessary.
- I can't think why we're using svg2rlg

**Comment by wjdp** [comment]
> I'm not convinced it's 100% accurate though 

There's one package on mine that doesn't show py3 but does work. Yeah it's not.

For stuff that's not needed in prod you could have a `requirements_dev.txt` for nice-to-have-for-dev packages

**Comment by davidtaylorhq** [comment]
This is ready to go, pending PR review by @tomtom5152

**Comment by davidtaylorhq** [comment]
This be done
