### ISSUE TITLE
Add payments to invoice PDFs

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#291]
These should be listed on the invoices we send down to treasury to give a full reference of what we know, as well as the outstanding balance.

Allows for the TEC adjustment thing to actually be useful.

Especially important once #283 is merged.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Sounds like a good idea to me

**Comment by nhyty** [comment]
Has this not been done?

**Comment by davidtaylorhq** [comment]
Yes, this is done
