### ISSUE TITLE
Email overflow on client auth panel in rig modal

### ISSUE THREAD

**Issue by harry-bridge** [nottinghamtec/PyRIGS#316]
Things overflow innit

**Comment by davidtaylorhq** [comment]
Use a bigger screen 😛

**Comment by harry-bridge** [comment]
I feel like chrome being 1600 * 930 is large enough 😛

**Comment by davidtaylorhq** [comment]
Ah, I guess that is fair 😉 
I think some `overflow: ellipsis` is in order

**Comment by FreneticScribbler** [comment]
Cannot confirm, may have been fixed by the change I did the other day?

**Comment by FreneticScribbler** [comment]
Cannot reproduce. Seems to be all pretty and overflow-ellipses-ed.
