### ISSUE TITLE
Event authorisation emails say None as the date

### ISSUE THREAD

**Issue by johnathan99j** [nottinghamtec/PyRIGS#321]
Both the MIC and client get the error.

![image](https://user-images.githubusercontent.com/15066398/33554701-be023200-d8f5-11e7-8e0a-db99ca533754.png)
-------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/15066398/33554747-e88b59a2-d8f5-11e7-8923-9922a2574c26.png)

**Comment by davidtaylorhq** [comment]
That's gone quite badly

**Comment by johnathan99j** [comment]
Indeed

**Comment by FreneticScribbler** [comment]
It took me way way way too long to notice that there was both a html and txt version of the client mail.
