### ISSUE TITLE
Generating Invoice Requests - Badly

### ISSUE THREAD

**Issue by johnathan99j** [nottinghamtec/PyRIGS#323]
Sometime when you go to print an invoice it will go the below. I've only had this happen a few times and it's only the first time I've tried to print it. Refreshing the page fixes it,

(screenshot removed)

**Comment by tomtom5152** [comment]
If it happens again, could you save the PDF so I can look into whats its actually doing please.

**Comment by johnathan99j** [comment]
Happened again. I've send you a copy of the PDF, but when I opened it in system viewer (Adobe Acrobat) and in chrome it was fine. Seems to just be the first time it loads/

**Comment by davidtaylorhq** [comment]
I've seen a lot of bugs in the chrome PDF viewer, could be related

**Comment by davidtaylorhq** [comment]
Have you seen this recently @johnathan99j ? Chrome has been making lots of changes to PDF viewer I believe so it might be fixed now

**Comment by johnathan99j** [comment]
I haven't, but then again I'm not really using that part of RIGS anymore since the handover. Will ask James to keep an eye out for it.

**Comment by davidtaylorhq** [comment]
Will close for now then, we can re-open if it happens again
