### ISSUE TITLE
Event authorisation warning on event duplication

### ISSUE THREAD

**Issue by johnathan99j** [nottinghamtec/PyRIGS#326]
![image](https://user-images.githubusercontent.com/15066398/37784415-affdac62-2def-11e8-8737-b5b4deaf1843.png)

**Comment by davidtaylorhq** [comment]
Is this purely a UI thing? Or is the event authorisation persisting when we duplicated events?

**Comment by johnathan99j** [comment]
Just UI

**Comment by johnathan99j** [comment]
Ok so had a quick look at this, the issue is that `EventDuplicate` calls `EventUpdate` first and the line which is causing the message is called from that class before the new event is made, this means that regardless of how much you clear when duplicating an event it will always show the message.

https://github.com/nottinghamtec/PyRIGS/blob/3c605d29768542831d137598db9e410138f5d1a3/RIGS/rigboard.py#L127-L128
