### ISSUE TITLE
Form validation needed on asset forms

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#342]
Form validation on the following forms are missing:

* Add asset
* Edit asset

Form validation that needs to be added:

* Items must have a status and category
* Asset IDs must be numeric (though not a problem as this will probably not be the user's choice to pick in the future anyway)
* Ensuring that the values are all valid to be entered into the database

**Comment by harry-bridge** [comment]
- Asset IDs must be numeric (though not a problem as this will probably not be the user's choice to pick in the future anyway)

Will fail when editing legacy assets, better to validate on regex that no special characters have been added

- Ensuring that the values are all valid to be entered into the database

Already checked in the form.is_valid() method, just needs something doing with it

**Comment by FreneticScribbler** [comment]
Copied and pasted from @mattysmith22

**Comment by FreneticScribbler** [comment]
N.b. Setting the 'Sold' category should require entering a sold date... :P 

EDIT: On second thoughts, it should probably suggest you enter one but not require it - i.e. let you save it without anyway, in case of something being updated as 'sold in the past'

**Comment by mattysmith22** [comment]
I have form validation working, for example an item cannot be sold before it is bought. I think a discussion upon what validation should take place would be good. I propose the following validation checks:

1) If asset_id is changed (meaning that it won't fail on legacy assets) then it must follow a certain validity check. This could be being entirely valid, or it can just be a regex check as @harry-bridge suggests.
2) An asset cannot be purchased in the future
3) Simple blocking of prices being negative

Are there any validations that I am missing here, or are any of these too overreaching?

**Comment by mattysmith22** [comment]
Additional validation - fail rather than truncate on when max length exceeded

**Comment by FreneticScribbler** [comment]
Putting commas in prices shouldn't reject the form, the commas should just be silently removed. Just for ease of use 😁

Should render with commas tho (use case for django-humanize)

**Comment by FreneticScribbler** [comment]
Should make the validation pretty (highlighting invalid fields etc) as well :D

**Comment by mattysmith22** [comment]
> commas should just be silently removed

That can easily be done, I will also implement that.

> Should make the validation pretty (highlighting invalid fields etc) as well
> Should render with commas tho (use case for django-humanize)

This is a frontend thing, definitely possible to implement!

**Comment by FreneticScribbler** [comment]
Yes I know the latter's a frontend thing that was a note to self :P

**Comment by mattysmith22** [comment]
Currently the failure of commas is a frontend thing too, the number field won't allow it through.

**Comment by FreneticScribbler** [comment]
Just leave as is, RIGS doesn't handle them either. It's a 'would be nice'

**Comment by mattysmith22** [comment]
Also, the truncation isn't server-side. It's client side - a maximum input on the textbox input

If you remove the client-side truncation (a maximum number of characters you can input) this occurs:
![image](https://user-images.githubusercontent.com/9770674/66426950-e7bce680-ea0a-11e9-9432-78f546be0347.png)

**Comment by FreneticScribbler** [comment]
I swear that's changed. Either way it's fine now.

**Comment by FreneticScribbler** [comment]
Resolved in b7e14b7dc394155610bc9d422374fafd96d9c243, we can reopen this if we find we need more validation.
