### ISSUE TITLE
Use 'https://assets.nottinghamtec.co.uk' subdomain

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#346]
Rewrite asset urls from 'https://rigs.nottinghamtec.co.uk/assets/*' to 'https://assets.nottinghamtec.co.uk/*'

**Comment by mattysmith22** [comment]
When we put multiple subdomains, how will we make it so it's still operable in debug scenarios (localhost) - different url configs?

**Comment by davidtaylorhq** [comment]
Is the plan to have multiple subdomains connected to the same django app? That sounds like a recipe for confusion!

**Comment by FreneticScribbler** [comment]
Assets and RIGS are different Django apps no?

I'm still looking at whether or not to do this because it does like like a giant PITA, but equally assets.nottinghamtec.co.uk feels cleaner than rigs.nottinghamtec.co.uk/assets/ to me... <sup>And pyTraining would be a lot nicer on training.nottinghamtec.co.uk than rigs.nottinghamtec.co.uk/training/....</sup>

**Comment by tomtom5152** [comment]
I haven’t been following this branch much, just occasionally reading issues, but my understanding was that this was to be a part of RIGS not a standalone thing, so therefore would logically come under rigs.nottinghamtec.co.uk/assets or similar. Different sub domains causes issues with cookies, routing, cross-origin policy and a whole host of other things. 
If you must have a sub domain for it, might I recommend a dumb forwarder much like wiki.

**Comment by FreneticScribbler** [comment]
Dumb forwarder is probably the answer

**Comment by davidtaylorhq** [comment]
> assets.nottinghamtec.co.uk feels cleaner than rigs.nottinghamtec.co.uk/assets/ 

I doubt you'll be saying that after trying to implement and debug that :P

Personally, I don't see any problem with assets and training sitting underneath rigs.nottinghamtec.co.uk. Ultimately TEC does rigs, and training/assets are pieces of information required to do rigs. Rig Information Gathering System 🎉

**Comment by FreneticScribbler** [comment]
> TEC does rigs

Apparently not these days! :stuck_out_tongue: :sob:
