### ISSUE TITLE
Fix AssetDB Buttons

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#347]
- [x] View button in asset list
- [x] Edit button in asset list
- [x] Duplicate button in asset list
- [x] Edit button in supplier list

**Comment by mattysmith22** [comment]
I will also be moving across the delete to a generic CBV, so that will change soon, I will handle that after the fact though.

**Comment by harry-bridge** [comment]
Always use the `{% url %}` tag to access by name, then you don't have to go around hunting for everywhere you've used it

**Comment by mattysmith22** [comment]
Yeah, we have been doing that so far. I was just providing both methods of access so he can look at the endpoint too before pointing to it if he chooses.

**Comment by FreneticScribbler** [comment]
This is fixed barring deletion, which is pending a Forum discussion.
