### ISSUE TITLE
Existing dates not shown when editing assets

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#349]
When editing assets with existing acquired/sold dates, they aren't shown in the form fields. I think this is because the database stores in DD-MM-YYYY format, whereas the \<input type="date"> expects a value in YYYY-MM-DD.

**Comment by mattysmith22** [comment]
Fixed in https://github.com/nottinghamtec/PyRIGS/commit/3d5272d7229cde9eb0a34d65fa9122f90991ae37 and https://github.com/nottinghamtec/PyRIGS/commit/3aa3498d3a19fe8a8ef96a366e86e3807046481f

**Comment by FreneticScribbler** [comment]
Coulda closed it from the commit :P
