### ISSUE TITLE
User access control on asseting

### ISSUE THREAD

**Issue by mattysmith22** [nottinghamtec/PyRIGS#352]
Currently, all a person needs to be is authenticated and they get full write access to the asset database. This should be hardened.

**Comment by FreneticScribbler** [comment]
View access to the database for anyone. Edit access for keyholders, I reckon.

**Comment by FreneticScribbler** [comment]
Probably not necessary to hide financials stuff for non-keyholders?

**Comment by FreneticScribbler** [comment]
Quickest solution would be to allow view access to the asset list to anyone signed in, but block anything else, including details (financials) behind keyholder permissions.

**Comment by FreneticScribbler** [comment]
Believe this was finished/changed in the storeroom, @mattysmith22 do you remember?

**Comment by mattysmith22** [comment]
Changes were made so we are 90% sure it works. just needs double checking by another person

**Comment by FreneticScribbler** [comment]
Calling done until someone complains.
