### ISSUE TITLE
Filters should support multiple options

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#353]
By no means essential, but probably nice to have

**Comment by FreneticScribbler** [comment]
Also move the filter selection to the table header. 

Also also, add date acquired to the asset list (and in future allow changing the sort to this)

**Comment by FreneticScribbler** [comment]
And filter out assets that are not in service by default :P

**Comment by mattysmith22** [comment]
Added a field to `AssetStatus` called `should_show`. This is default `True` and when `False` it hides any items from that category unless told otherwise. I thought this was more future-proof than hard-coding it.
