### ISSUE TITLE
Prefill asset ID in creation form with 'recommended' ID

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#356]
Next free ID. Without trying to gapfill from previous IDs?

**Comment by mattysmith22** [comment]
So if someone randomly puts an asset ID as 1,000,000 it would autofill the next as 1,000,001?

**Comment by mattysmith22** [comment]
Added in https://github.com/nottinghamtec/PyRIGS/commit/8ec27eb0751e23d0f1833cb3c73acbc7ceed0451

This was written so that it would find the next available number over 9000. This is currently hard-coded as a value, but could be added as a setting in the future.
