### ISSUE TITLE
Production Tasks

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#360]
An issue to track misc things that need to be done before we're ready for production

- [x] Subdomain forwarder
- [x] Old database import
- [x] Clean up duplicates from old data

**Comment by harry-bridge** [comment]
I have a sql dump of the old assets database, also there is a management command to import the old DB, but you also need the old old db dump for that

**Comment by FreneticScribbler** [comment]
Ah good point - can I have the thing please :P

**Comment by harry-bridge** [comment]
Yes, just need to find the right one as i've helpfully not labelled the ones I took through the development I did

**Comment by FreneticScribbler** [comment]
Poke @harry-bridge
