### ISSUE TITLE
Subcategories

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#379]
Considering the current mess of categories I think there's a case for hierarchical subcats.

**Comment by mattysmith22** [comment]
What's the issue with doing stuff like `lighting - generic` and `lighting - intelligent`? If they're sorted alphanumerically they will appear sequentially

**Comment by FreneticScribbler** [comment]
No issue - I suppose that they're a lot less necessary when the testing stuff is in. I guess we don't have that much stuff...
