### ISSUE TITLE
Migrate python dependancies to pipenv

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#384]
Have been using this a lot recently and it makes life so much easier than using just pip with virtualenvs. Might be worth transitioning at some point.

**Comment by wjdp** [comment]
@tomtom5152 Have been using pipenv on and off for the last year. It is better in some ways, and worse in others. Often locking and other operations are very slow and there are some UX weirdnesses. Still a net positive, I think, but have a Google and a play before jumping on this too quick.

Have seen a movement to https://poetry.eustace.io/ which I have zero idea about.

**Comment by FreneticScribbler** [comment]
Just mucked about with this, I like it

**Comment by tomtom5152** [comment]
I was about to reply saying how lovely pipenv is to work with, then I remembered I opened an issue like this somewhere and was surprised to learn the thread was mine from a while ago. My opinion still stands, it makes life a lot easier.

**Comment by FreneticScribbler** [comment]
Cor, locking is indeed slow though

**Comment by wjdp** [comment]
I'm using [poetry](https://python-poetry.org/) for personal stuff now, is very nice, and [pip-tools](https://github.com/jazzband/pip-tools) at work which is better than managing raw `requirements.txt` but only half way.

Gave up on pipenv a while ago.

**Comment by FreneticScribbler** [comment]
*screams gently*

So Heroku's python buildpack locks pip to version 9 (!!) when using pipenv for.........................reasons. Fun! Current pip version at time of writing is 21!
