### ISSUE TITLE
Asset Database Discourse Onebox

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#392]
Presumably this is implemented Discourse side rather than PyRIGS side but still makes sense on this tracker given its a feature for this.

**Comment by davidtaylorhq** [comment]
No changes required in Discourse, this is handled 100% on the pyrigs side, using the oembed standard :)

**Comment by FreneticScribbler** [comment]
Trust me to get it backwards :P
