### ISSUE TITLE
Changes to Travis

### ISSUE THREAD

**Issue by alexdaniel654** [nottinghamtec/PyRIGS#415]
I've just been "upgraded" to Travis.com's "free plan" which is basically enough credits to keep going until you can pay them some money i.e. they never top up your credits. The only way of getting free travis after November is to convince them your project is worthy of free credits which is done on a case by case basis. More info [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). 

I know RIGS is on travis.org, but that's going away at the end of this year anyway. Long and short of it, this is a heads up that something is going to need to happen to your CI in the next couple of months.

**Comment by FreneticScribbler** [comment]
Probably Github Actions is the way... will look into it when I get sufficiently bored

**Comment by FreneticScribbler** [comment]
Wonder if I can do something clever like run the tests for the different apps in parallel to speed them up... (just adding the parallel flag causes the DB to lock up almost immediately) 
Just happy it works for now.
