### ISSUE TITLE
User merge functionality required

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#473]
Training DB has left a couple accounts, such as Duplo and NP, duplicated, so we need to be able to merge these. Not sure if that will just work :tm: with existing merge logic because of passwords.

**Comment by jerbzz** [comment]
Should we not just purge NP's records and account(s)?
I'm assuming he won't ever be welcome back.

**Comment by FreneticScribbler** [comment]
Probably. Not a conversation to have on GitHub either way!

**Comment by FreneticScribbler** [comment]
Doesn't preserve reverse relations (e.g. when merge user is a supervisor of x qualification)
