### ISSUE TITLE
Editing a combobox in Add Session causes an error on form submission

### ISSUE THREAD

**Issue by jerbzz** [nottinghamtec/PyRIGS#501]
![310231570_820993332561577_8318014364449990771_n](https://user-images.githubusercontent.com/28573604/197290529-fe151fba-0484-43e6-bd68-2a79c082b8d6.png)

**Comment by FreneticScribbler** [comment]
This worked the other day didn't it? I wonder what changed...

**Comment by jerbzz** [comment]
No, it's done this since I've been messing with it. Coudn't figure out why at first though :P

**Comment by FreneticScribbler** [comment]
So how did it work for submitting stuff from the other day? I'm a little confused.
Do you mean if you enter some stuff in the combobox, click out, then go back and change it, it errors out when you submit? I.e. you have to get it right the first time?

**Comment by jerbzz** [comment]
Yes, exactly that. Put some training items in, realise one is wrong, remove that one, submit, get the error. No issues if you do it right first time.

**Comment by FreneticScribbler** [comment]
Looks like this is fixed.
