### ISSUE TITLE
Supervisors of Haulage shouldn't be able to see the RA 'Mark Reviewed' button

### ISSUE THREAD

**Issue by BenWoodford76** [nottinghamtec/PyRIGS#528]
As a Supervisor of Haulage I probably shouldn't be able to see the 'Mark Reviewed' button.

![image](https://user-images.githubusercontent.com/18663231/228331849-56d5bc2e-d40b-4aa7-9327-6b135b66f5a0.png)

**Comment by FreneticScribbler** [comment]
Note to self: Need to double check that the "is_supervisor" flag is *not* set when someone becomes a Supervisor of Haulage...

**Comment by FreneticScribbler** [comment]
Yeah I don't know why this is happening, supervisors of haulage are indeed not considered "full supervisors". 

But I changed the logic around this anyway so...probably fixed?
