### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by alexdaniel654** [nottinghamtec/PyRIGS#587]
All the icons seem to have gone, I just get a box in the appropriate color. Been happening for a day or so across multiple devices and internet connections i.e. its not just work blocking something silly.

![image](https://github.com/nottinghamtec/PyRIGS/assets/23356429/21685d25-9466-47b5-a2b6-69fef6e96179)
![image](https://github.com/nottinghamtec/PyRIGS/assets/23356429/378a790c-c9be-4f70-b582-8287e1d97b06)
![image](https://github.com/nottinghamtec/PyRIGS/assets/23356429/48868397-9590-4b74-9ac7-16f70d9c0419)

**Comment by alexdaniel654** [comment]
Doesn't seem to have been fixed by 70abfaf2aee2050a37b7fe7e487e77e2ec6d8faf.

**Comment by FreneticScribbler** [comment]
Indeed. Didn't mean to close it anyways, Github automation got me.

 8246071 is a fix but I can't deploy it with this random answer generator test suite. >.>

**Comment by bobbinz** [comment]
I think this was a chrome bug in the end. Seems fixed now anyways!

**Comment by FreneticScribbler** [comment]
It was, convolutely, javascript's fault. But yes, should now be resolved.
