### ISSUE TITLE
Strikethrough in Notes section

### ISSUE THREAD

**Issue by Ethsim12** [nottinghamtec/PyRIGS#592]
~~strikethrough text~~ doesn't work in notes section, Whereas in description section it does?

**Comment by jb3** [comment]
I can't see it working in either section, whilst the markdown editor embed thing supports it, I don't think the Django `markdown` filter we have made does.

Markdown spec technically does not have strikethroughs: https://spec.commonmark.org/0.31.2/

Flavors of markdown like GFM do, hence why you can use it on GitHub and seemingly in the editor we use.

If this *actually* is working in one place and not the other, I am very interested, but testing locally I can't get it to work in either and the library we use does not seem to have strikethroughs in it's reference implementation.

**Comment by Ethsim12** [comment]
> Blockquote [foo].
> https://rigs.nottinghamtec.co.uk/user/
> [foo]: /url

Hi Joe,

Thank you for your reply.

I'm trying to find the data sections of a Rig where this issue was experienced, and have a couple of questions;

- Can you see a HTML kit list in [here](https://rigs.nottinghamtec.co.uk/event/6619/)?
- It was probably this rig [here](https://rigs.nottinghamtec.co.uk/event/6620/) that was where i couldn't strikethrough in description section?

- I can't see the edit history for either of these rigs, can you reproduce locally?

**Comment by jb3** [comment]
> Can you see a HTML kit list in [here](https://rigs.nottinghamtec.co.uk/event/6619/)?

HTML is rendered here, yes. We do support a lot of Markdown, we just don't support strikethroughs.

Neither description or notes will support description since they go through the same `markdown` custom filter.

**Comment by jb3** [comment]
We use [this library](https://python-markdown.github.io/) which implements [this subset of markdown](https://daringfireball.net/projects/markdown/syntax). Everything in that reference should be supported, so you will see emphasis is supported but not strikethroughs.

**Comment by jb3** [comment]
Closing for now. Holding onto "previously relevant content" is handled by the revision system and I don't think that strikethroughs will help us in the long run.

For various reasons from crew rotas to health & safety chains of responsibility information presented through RIGS should be current and the latest available version, we should remove all potential causes of doubt.
