### ISSUE TITLE
CI builder python version issue

### ISSUE THREAD

**Issue by nickw29** [nottinghamtec/PyRIGS#597]
CI builder fails due to setting up python 3.9 whilst the Pipfile requires 3.10

**Comment by jb3** [comment]
Should be fixed with some other miscellaneous packaging issues in #598.

Long term I'd like to switch to Poetry given the stagnation, speed and other issues with `pipenv` and things are mostly compatible

**Comment by FreneticScribbler** [comment]
> Long term I'd like to switch to Poetry

And around again we go :laughing:
