### ISSUE TITLE
User ordering in admin panel

### ISSUE THREAD

**Issue by jb3** [nottinghamtec/PyRIGS#605]
As requested by Jerbs on the forum.

We can use the `date_created` field on the user model as long as it can be exposed in the admin panel.

I'll look at it soon, this is just a tracking issue so I remember.

**Comment by jerbzz** [comment]
Don't break it this time Joe @jb3 🤣

**Comment by jb3** [comment]
I've had my trial by fire with RIGS remediations 🤣, no more trusting the stochastic test suite.
